name:  Gitleaks

on:
  push:
    branches:
      -main vuln√©rable-flash-app.py
jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
     name: Checkout Repository
      uses: cxrxl/labdevsecops  

name: Install Gitleaks
      run: |
        wget https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks-linux-amd64 -O gitleaks
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/
        gitleaks --version

name: Run Gitleaks
run: gitleaks --path . --verbose

      
